### PR TITLE
auth module design-1

### PR DESCRIPTION
**Pull request by gyedasys**
PR contains auth designs

### CODE REVIEW

**Comment by usamaidrsk** [comment]
@gyedasys , if you would add screenshots it would be the best, thanks

**Review by usamaidrsk — COMMENTED** [review]
nice work, please add some screenshots

**Comment by gyedasys** [comment]
please, review and make commentss where necessary so that i continue with my work. otherwise, you are blocking me

**Review by usamaidrsk — APPROVED** [review]

**Comment by usamaidrsk** [comment]
I've approved though i the screenshots I've not seen the emplyee signup page, was it mwant to be part, or it's coming soon

**Comment by nsengiyumva-wilberforce** [comment]
Register employee is missing

**Comment by gyedasys** [comment]
its there

**Pull request merged**
